# -*- coding: utf-8 -*-
"""a와 b 출력하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12t0S1U7m7W1nF_ktp-_KAwTn3eH42_IL

# a와 b 출력하기

### 문제 설명
 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.


### 제한사항

 -100,000 ≤ a, b ≤ 100,000



### 입출력 예

 입력 #1

 4 5

 출력 #1

 a = 4

 b = 5
"""

a, b = map(int, input().strip().split(' '))
print("a =",a)
print("b =",b)

# input() 함수를 사용하여 사용자로부터 키보드 입력을 받습니다.
# .strip() 메서드를 사용하여 입력 문자열의 양쪽 공백을 제거합니다.
# .split(' ') 메서드를 사용하여 입력 문자열을 공백을 기준으로 나눕니다. 즉, 입력 문자열을 공백으로 구분된 여러 부분으로 나눠서 리스트로 만듭니다.
# map(int, ...)를 사용하여 나뉜 각 부분을 정수로 변환합니다.